service: serverless-api-example

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION, 'ca-central-1'}
  runtime: nodejs14.x

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

functions:
  api:
    handler: src/api.handler
    events:
      - httpApi: '*'
